apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo2
spec:
  hostPID: true
  containers:
  - name: sec-ctx-demo2
    image: busybox
    command: ["sh", "-c", "sleep 1h"]
    securityContext:
      capabilities:
        add: ["NET_ADMIN"]
        drop: ["CHOWN"]

